export interface Judgment {
  id: string;
  title: string;
  citation: string;
  court: string;
  date: string;
  year: number;
  bench: string;
  judges: string[];
  petitioner: string;
  respondent: string;
  topic: string[];
  acts: string[];
  headnote: string;
  aiSummary: string;
  fullText: string;
  pdfUrl?: string;
  isNew?: boolean;
}

export interface BareAct {
  id: string;
  title: string;
  shortTitle: string;
  year: number;
  ministry: string;
  category: string;
  sections: number;
  description: string;
  lastAmended: string;
}

export interface CourtFilter {
  id: string;
  name: string;
  shortName: string;
  state?: string;
  established?: number;
  website?: string;
  location?: string;
}

export interface DailyUpdate {
  id: string;
  title: string;
  court: string;
  date: string;
  topic: string[];
  citation: string;
  summary: string;
  isNew: boolean;
}

export const courts: CourtFilter[] = [
  { id: "sc", name: "Supreme Court of India", shortName: "SC", established: 1950, location: "New Delhi", website: "https://main.sci.gov.in" },
  { id: "hc-all", name: "Allahabad High Court", shortName: "Allahabad HC", state: "Uttar Pradesh", established: 1866, location: "Prayagraj", website: "https://www.allahabadhighcourt.in" },
  { id: "hc-ap", name: "Andhra Pradesh High Court", shortName: "AP HC", state: "Andhra Pradesh", established: 2019, location: "Amaravati", website: "https://hc.ap.nic.in" },
  { id: "hc-bom", name: "Bombay High Court", shortName: "Bombay HC", state: "Maharashtra", established: 1862, location: "Mumbai", website: "https://bombayhighcourt.nic.in" },
  { id: "hc-cal", name: "Calcutta High Court", shortName: "Calcutta HC", state: "West Bengal", established: 1862, location: "Kolkata", website: "https://calcuttahighcourt.gov.in" },
  { id: "hc-chh", name: "Chhattisgarh High Court", shortName: "Chhattisgarh HC", state: "Chhattisgarh", established: 2000, location: "Bilaspur", website: "https://highcourt.cg.gov.in" },
  { id: "hc-del", name: "Delhi High Court", shortName: "Delhi HC", state: "Delhi", established: 1966, location: "New Delhi", website: "https://delhihighcourt.nic.in" },
  { id: "hc-gau", name: "Gauhati High Court", shortName: "Gauhati HC", state: "Assam, Nagaland, Meghalaya, Manipur, Tripura, Mizoram, Arunachal Pradesh", established: 1948, location: "Guwahati", website: "https://ghconline.gov.in" },
  { id: "hc-guj", name: "Gujarat High Court", shortName: "Gujarat HC", state: "Gujarat", established: 1960, location: "Ahmedabad", website: "https://gujarathighcourt.nic.in" },
  { id: "hc-him", name: "Himachal Pradesh High Court", shortName: "HP HC", state: "Himachal Pradesh", established: 1971, location: "Shimla", website: "https://hphighcourt.nic.in" },
  { id: "hc-jk", name: "Jammu & Kashmir and Ladakh High Court", shortName: "J&K HC", state: "J&K and Ladakh", established: 1943, location: "Srinagar / Jammu", website: "https://jkhighcourt.nic.in" },
  { id: "hc-jha", name: "Jharkhand High Court", shortName: "Jharkhand HC", state: "Jharkhand", established: 2000, location: "Ranchi", website: "https://jharkhandhighcourt.nic.in" },
  { id: "hc-kar", name: "Karnataka High Court", shortName: "Karnataka HC", state: "Karnataka", established: 1884, location: "Bengaluru", website: "https://karnatakajudiciary.kar.nic.in" },
  { id: "hc-ker", name: "Kerala High Court", shortName: "Kerala HC", state: "Kerala", established: 1956, location: "Ernakulam", website: "https://highcourt.kerala.gov.in" },
  { id: "hc-mp", name: "Madhya Pradesh High Court", shortName: "MP HC", state: "Madhya Pradesh", established: 1956, location: "Jabalpur", website: "https://mphc.gov.in" },
  { id: "hc-mad", name: "Madras High Court", shortName: "Madras HC", state: "Tamil Nadu", established: 1862, location: "Chennai", website: "https://www.hcmadras.tn.nic.in" },
  { id: "hc-man", name: "Manipur High Court", shortName: "Manipur HC", state: "Manipur", established: 2013, location: "Imphal", website: "https://mhc.nic.in" },
  { id: "hc-meg", name: "Meghalaya High Court", shortName: "Meghalaya HC", state: "Meghalaya", established: 2013, location: "Shillong", website: "https://meghalayahighcourt.nic.in" },
  { id: "hc-ori", name: "Orissa High Court", shortName: "Orissa HC", state: "Odisha", established: 1948, location: "Cuttack", website: "https://orissahighcourt.nic.in" },
  { id: "hc-pat", name: "Patna High Court", shortName: "Patna HC", state: "Bihar", established: 1916, location: "Patna", website: "https://patnahighcourt.gov.in" },
  { id: "hc-ph", name: "Punjab & Haryana High Court", shortName: "P&H HC", state: "Punjab, Haryana, Chandigarh", established: 1947, location: "Chandigarh", website: "https://highcourtchd.gov.in" },
  { id: "hc-raj", name: "Rajasthan High Court", shortName: "Rajasthan HC", state: "Rajasthan", established: 1949, location: "Jodhpur", website: "https://hcraj.nic.in" },
  { id: "hc-sik", name: "Sikkim High Court", shortName: "Sikkim HC", state: "Sikkim", established: 1975, location: "Gangtok", website: "https://sikkim.gov.in/judiciary" },
  { id: "hc-tel", name: "Telangana High Court", shortName: "Telangana HC", state: "Telangana", established: 2019, location: "Hyderabad", website: "https://hc.ts.nic.in" },
  { id: "hc-tri", name: "Tripura High Court", shortName: "Tripura HC", state: "Tripura", established: 2013, location: "Agartala", website: "https://tripurahighcourt.gov.in" },
  { id: "hc-utt", name: "Uttarakhand High Court", shortName: "Uttarakhand HC", state: "Uttarakhand", established: 2000, location: "Nainital", website: "https://uttarakhandhighcourt.nic.in" },
];

export const topics = [
  "Constitutional Law", "Criminal Law", "Civil Law", "Family Law",
  "Property Law", "Contract Law", "Labour Law", "Tax Law",
  "Environmental Law", "Intellectual Property", "Company Law",
  "Banking & Finance", "Arbitration", "Human Rights",
];

export const judgments: Judgment[] = [
  {
    id: "j001",
    title: "Kesavananda Bharati v. State of Kerala",
    citation: "(1973) 4 SCC 225",
    court: "Supreme Court of India",
    date: "24 April 1973",
    year: 1973,
    bench: "13-Judge Constitutional Bench",
    judges: ["Justice Y.V. Chandrachud", "Justice K.S. Hegde", "Justice A.K. Mukherjea", "Justice J.M. Shelat"],
    petitioner: "His Holiness Kesavananda Bharati Sripadagalvaru",
    respondent: "State of Kerala",
    topic: ["Constitutional Law", "Human Rights"],
    acts: ["Constitution of India", "Kerala Land Reforms Act, 1963"],
    headnote: "Parliament's power to amend the Constitution does not extend to altering or destroying its basic structure.",
    aiSummary: "This landmark 13-judge bench ruling established the 'Basic Structure Doctrine' of the Indian Constitution. The court held that while Parliament has wide powers to amend the Constitution under Article 368, such amendments cannot destroy or abrogate the basic structure or framework of the Constitution. Key basic features include: supremacy of the Constitution, republican and democratic form of government, secular character, separation of powers, and federal character. This case overruled the earlier Golak Nath judgment and remains the cornerstone of Indian constitutional law.",
    fullText: "In this landmark judgment, a 13-judge bench of the Supreme Court, by a razor-thin majority of 7:6, held that the Parliament has the power to amend the Constitution but cannot alter or destroy its basic structure.",
    pdfUrl: "https://main.sci.gov.in/judgment/judis/9267.pdf",
  },
  {
    id: "j002",
    title: "Maneka Gandhi v. Union of India",
    citation: "(1978) 1 SCC 248",
    court: "Supreme Court of India",
    date: "25 January 1978",
    year: 1978,
    bench: "7-Judge Bench",
    judges: ["Justice P.N. Bhagwati", "Justice Y.V. Chandrachud", "Justice V.R. Krishna Iyer"],
    petitioner: "Maneka Gandhi",
    respondent: "Union of India",
    topic: ["Constitutional Law", "Human Rights"],
    acts: ["Constitution of India - Article 21", "Passports Act, 1967"],
    headnote: "Article 21 procedure must be fair, just, and reasonable. Right to life and liberty includes right to travel abroad.",
    aiSummary: "The Supreme Court expanded the scope of Article 21 significantly. It held that the 'procedure established by law' must be fair, just, and reasonable — not arbitrary, fanciful, or oppressive. The court ruled that the right to travel abroad is part of personal liberty under Article 21.",
    fullText: "The petitioner's passport was impounded by the Government of India without giving her an opportunity to be heard...",
  },
  {
    id: "j003",
    title: "Vishaka v. State of Rajasthan",
    citation: "(1997) 6 SCC 241",
    court: "Supreme Court of India",
    date: "13 August 1997",
    year: 1997,
    bench: "3-Judge Bench",
    judges: ["Justice J.S. Verma", "Justice Sujata Manohar", "Justice B.N. Kirpal"],
    petitioner: "Vishaka & Others",
    respondent: "State of Rajasthan",
    topic: ["Human Rights", "Labour Law", "Constitutional Law"],
    acts: ["Constitution of India - Articles 14, 19, 21", "CEDAW"],
    headnote: "Sexual harassment at workplace violates fundamental rights. Mandatory guidelines issued for prevention.",
    aiSummary: "This path-breaking judgment laid down the Vishaka Guidelines for prevention of sexual harassment of women at the workplace. Treating sexual harassment as a violation of fundamental rights under Articles 14, 19, and 21, the Supreme Court issued binding guidelines that remained in force until the POSH Act, 2013 was enacted.",
    fullText: "This public interest litigation was filed following the gang-rape of Bhanwari Devi, a social worker in Rajasthan...",
  },
  {
    id: "j004",
    title: "Navtej Singh Johar v. Union of India",
    citation: "(2018) 10 SCC 1",
    court: "Supreme Court of India",
    date: "6 September 2018",
    year: 2018,
    bench: "5-Judge Constitutional Bench",
    judges: ["CJI Dipak Misra", "Justice R.F. Nariman", "Justice A.M. Khanwilkar", "Justice D.Y. Chandrachud", "Justice Indu Malhotra"],
    petitioner: "Navtej Singh Johar",
    respondent: "Union of India",
    topic: ["Constitutional Law", "Human Rights", "Criminal Law"],
    acts: ["Indian Penal Code - Section 377", "Constitution of India"],
    headnote: "Section 377 IPC unconstitutional to the extent it criminalises consensual sexual conduct between adults in private.",
    aiSummary: "The Supreme Court unanimously struck down Section 377 of the Indian Penal Code to the extent it criminalised consensual sexual conduct between adults. The bench held that the LGBTQ+ community is entitled to equal citizenship and dignity.",
    fullText: "A Constitution Bench of the Supreme Court delivered four separate but concurring opinions unanimously holding that consensual sexual conduct between adults in private cannot be criminalised...",
  },
  {
    id: "j005",
    title: "K.S. Puttaswamy v. Union of India",
    citation: "(2017) 10 SCC 1",
    court: "Supreme Court of India",
    date: "24 August 2017",
    year: 2017,
    bench: "9-Judge Constitutional Bench",
    judges: ["CJI J.S. Khehar", "Justice D.Y. Chandrachud", "Justice J. Chelameswar", "Justice S.A. Bobde"],
    petitioner: "Justice K.S. Puttaswamy (Retd.)",
    respondent: "Union of India",
    topic: ["Constitutional Law", "Human Rights"],
    acts: ["Constitution of India - Article 21", "Aadhaar Act, 2016"],
    headnote: "Right to privacy is a fundamental right under Article 21 of the Constitution.",
    aiSummary: "In this historic unanimous judgment, the Supreme Court declared that the right to privacy is a fundamental right protected under Article 21 of the Constitution. The judgment overruled earlier decisions in M.P. Sharma and Kharak Singh that had denied constitutional status to privacy.",
    fullText: "A nine-judge constitutional bench was constituted to decide whether the right to privacy is a fundamental right under the Constitution of India...",
  },
  {
    id: "j006",
    title: "Arnesh Kumar v. State of Bihar",
    citation: "(2014) 8 SCC 273",
    court: "Supreme Court of India",
    date: "2 July 2014",
    year: 2014,
    bench: "2-Judge Bench",
    judges: ["Justice Chandramauli Kumar Prasad", "Justice Pinaki Chandra Ghose"],
    petitioner: "Arnesh Kumar",
    respondent: "State of Bihar & Another",
    topic: ["Criminal Law", "Human Rights"],
    acts: ["Indian Penal Code - Section 498A", "Code of Criminal Procedure - Section 41"],
    headnote: "Arrest not mandatory for offences punishable with imprisonment less than 7 years. Magistrate must apply mind before authorising detention.",
    aiSummary: "The Supreme Court issued detailed guidelines to curb indiscriminate arrests under Section 498A IPC. The court held that police must satisfy conditions under Section 41 CrPC before arresting any person and must record reasons in writing.",
    fullText: "The petitioner challenged his arrest under Section 498A IPC on a complaint by his wife...",
  },
  {
    id: "j007",
    title: "Indian Young Lawyers Association v. State of Kerala",
    citation: "(2019) 11 SCC 1",
    court: "Supreme Court of India",
    date: "28 September 2018",
    year: 2018,
    bench: "5-Judge Constitutional Bench",
    judges: ["CJI Dipak Misra", "Justice R.F. Nariman", "Justice A.M. Khanwilkar", "Justice D.Y. Chandrachud", "Justice Indu Malhotra"],
    petitioner: "Indian Young Lawyers Association",
    respondent: "State of Kerala",
    topic: ["Constitutional Law", "Human Rights"],
    acts: ["Constitution of India - Articles 14, 15, 17, 25, 26"],
    headnote: "Exclusion of women from Sabarimala temple is unconstitutional and violates Articles 14, 15, and 17.",
    aiSummary: "A 4:1 majority held that the practice of excluding women between 10-50 years of age from the Sabarimala temple was unconstitutional. The majority held that constitutional morality must prevail over popular morality.",
    fullText: "A constitutional bench was constituted to examine the validity of the centuries-old practice of excluding women of menstruating age from the Sabarimala temple...",
  },
  {
    id: "j008",
    title: "Lalita Kumari v. Government of U.P.",
    citation: "(2014) 2 SCC 1",
    court: "Supreme Court of India",
    date: "12 November 2013",
    year: 2013,
    bench: "5-Judge Constitutional Bench",
    judges: ["CJI P. Sathasivam", "Justice B.S. Chauhan", "Justice Ranjana Prakash Desai", "Justice Ranjan Gogoi", "Justice S.A. Bobde"],
    petitioner: "Lalita Kumari",
    respondent: "Government of Uttar Pradesh",
    topic: ["Criminal Law"],
    acts: ["Code of Criminal Procedure - Section 154"],
    headnote: "Registration of FIR is mandatory under Section 154 CrPC if disclosed information reveals cognizable offence.",
    aiSummary: "The Supreme Court settled the long-standing controversy over whether registration of FIR is mandatory. A five-judge bench held that registration of FIR is mandatory if information discloses commission of a cognizable offence.",
    fullText: "A minor girl's father filed a petition when police refused to register an FIR for his daughter's abduction...",
  },
  {
    id: "j009",
    title: "Shayara Bano v. Union of India",
    citation: "(2017) 9 SCC 1",
    court: "Supreme Court of India",
    date: "22 August 2017",
    year: 2017,
    bench: "5-Judge Constitutional Bench",
    judges: ["CJI J.S. Khehar", "Justice Kurian Joseph", "Justice R.F. Nariman", "Justice U.U. Lalit", "Justice S. Abdul Nazeer"],
    petitioner: "Shayara Bano",
    respondent: "Union of India",
    topic: ["Family Law", "Constitutional Law", "Human Rights"],
    acts: ["Muslim Personal Law", "Constitution of India - Articles 14, 15, 21"],
    headnote: "Triple talaq (talaq-e-biddat) is unconstitutional and manifestly arbitrary.",
    aiSummary: "A 3:2 majority struck down the practice of triple talaq (instantaneous divorce by uttering 'talaq' thrice) as unconstitutional. Justice Nariman and Lalit held it violated Article 14 being manifestly arbitrary. This led to the Muslim Women (Protection of Rights on Marriage) Act, 2019.",
    fullText: "The petitioner challenged the practice of triple talaq after her husband divorced her by sending a WhatsApp message containing the word 'talaq' three times...",
    isNew: false,
  },
  {
    id: "j010",
    title: "Joseph Shine v. Union of India",
    citation: "(2019) 3 SCC 39",
    court: "Supreme Court of India",
    date: "27 September 2018",
    year: 2018,
    bench: "5-Judge Constitutional Bench",
    judges: ["CJI Dipak Misra", "Justice R.F. Nariman", "Justice A.M. Khanwilkar", "Justice D.Y. Chandrachud", "Justice Indu Malhotra"],
    petitioner: "Joseph Shine",
    respondent: "Union of India",
    topic: ["Criminal Law", "Constitutional Law", "Human Rights"],
    acts: ["Indian Penal Code - Section 497"],
    headnote: "Section 497 IPC (adultery) unconstitutional — treats women as property of husband.",
    aiSummary: "The Supreme Court unanimously struck down Section 497 IPC (adultery) as unconstitutional. The court held it was based on the notion that a woman is the property of her husband and violated Articles 14, 15, and 21. Women cannot be prosecuted for adultery under IPC.",
    fullText: "A constitutional bench unanimously decriminalized adultery, striking down a 158-year-old colonial law...",
  },
  {
    id: "j011",
    title: "Sarika v. State of Uttar Pradesh",
    citation: "2024 SCCOnLine All 542",
    court: "Allahabad High Court",
    date: "15 March 2024",
    year: 2024,
    bench: "Single Judge Bench",
    judges: ["Justice Saurabh Srivastava"],
    petitioner: "Sarika",
    respondent: "State of Uttar Pradesh",
    topic: ["Criminal Law", "Human Rights"],
    acts: ["Code of Criminal Procedure - Section 482", "POCSO Act, 2012"],
    headnote: "Quashing of FIR in POCSO cases requires compelling reasons; mere settlement between parties not sufficient.",
    aiSummary: "The Allahabad High Court held that FIRs in POCSO cases cannot be quashed merely because the parties have reached a settlement. The court emphasised that POCSO offences are serious crimes against society and not just against the individual victim. Settlement between parties does not override the State's duty to prosecute.",
    fullText: "The petitioner sought quashing of FIR registered under POCSO Act on the ground that parties had reached a compromise...",
    isNew: true,
  },
  {
    id: "j012",
    title: "Tech Mahindra Ltd. v. Special Director, ED",
    citation: "2024 SCCOnLine Del 1823",
    court: "Delhi High Court",
    date: "22 February 2024",
    year: 2024,
    bench: "Division Bench",
    judges: ["Justice Suresh Kumar Kait", "Justice Manoj Jain"],
    petitioner: "Tech Mahindra Ltd.",
    respondent: "Special Director, Enforcement Directorate",
    topic: ["Criminal Law", "Company Law"],
    acts: ["Prevention of Money Laundering Act, 2002"],
    headnote: "Corporate entity cannot be prosecuted under PMLA without evidence of proceeds of crime flowing into it.",
    aiSummary: "The Delhi High Court granted relief to Tech Mahindra, holding that the ED must establish that proceeds of crime have flowed into the corporate entity before initiating prosecution under PMLA. Mere allegations without prima facie evidence are not sufficient.",
    fullText: "The petitioner challenged summons issued by the Enforcement Directorate under the Prevention of Money Laundering Act...",
    isNew: true,
  },
  {
    id: "j013",
    title: "Anand Kumar Mohatta v. State (Delhi)",
    citation: "2024 SCCOnLine Del 824",
    court: "Delhi High Court",
    date: "8 February 2024",
    year: 2024,
    bench: "Single Judge",
    judges: ["Justice Navin Chawla"],
    petitioner: "Anand Kumar Mohatta",
    respondent: "State (NCT of Delhi)",
    topic: ["Criminal Law", "Family Law"],
    acts: ["Indian Penal Code - Section 498A", "Domestic Violence Act"],
    headnote: "WhatsApp messages constitute sufficient evidence of cruelty in matrimonial disputes.",
    aiSummary: "The Delhi High Court held that WhatsApp messages exchanged between parties can constitute sufficient evidence of mental cruelty in matrimonial disputes under Section 498A IPC. Electronic evidence must be read in context and the court should not look for only physical violence.",
    fullText: "The petitioner sought anticipatory bail in a matrimonial dispute where the complainant alleged cruelty based on WhatsApp conversations...",
    isNew: true,
  },
  {
    id: "j014",
    title: "M/s Amazon Seller Services Pvt. Ltd. v. Amway India",
    citation: "2024 SCCOnLine Bom 312",
    court: "Bombay High Court",
    date: "19 March 2024",
    year: 2024,
    bench: "Division Bench",
    judges: ["Justice G.S. Kulkarni", "Justice Jitendra Jain"],
    petitioner: "Amazon Seller Services Pvt. Ltd.",
    respondent: "Amway India Enterprises",
    topic: ["Contract Law", "Company Law", "Intellectual Property"],
    acts: ["Trade Marks Act, 1999", "Consumer Protection Act, 2019"],
    headnote: "Online marketplace platforms not liable for trademark infringement by third-party sellers unless they have actual knowledge.",
    aiSummary: "The Bombay High Court clarified the liability of online marketplace platforms in trademark infringement cases. The court held that mere hosting of third-party sellers does not make the platform liable for trademark violations unless it has actual knowledge of the infringement and fails to take it down.",
    fullText: "Amway India sought an injunction against Amazon, alleging that third-party sellers on the platform were selling its products in violation of trademark rights...",
    isNew: true,
  },
  {
    id: "j015",
    title: "Senthil Balaji v. State of Tamil Nadu",
    citation: "(2023) SCC OnLine SC 934",
    court: "Supreme Court of India",
    date: "26 July 2023",
    year: 2023,
    bench: "3-Judge Bench",
    judges: ["Justice A.S. Bopanna", "Justice M.M. Sundresh"],
    petitioner: "Senthil Balaji",
    respondent: "State of Tamil Nadu & ED",
    topic: ["Criminal Law", "Constitutional Law"],
    acts: ["Prevention of Money Laundering Act, 2002", "Constitution of India - Article 21"],
    headnote: "Minister arrested under PMLA; cabinet post does not grant immunity. Article 21 rights continue during investigation.",
    aiSummary: "The Supreme Court dismissed the habeas corpus petition of the Tamil Nadu Minister challenging his arrest under PMLA, holding that a cabinet minister does not have any special immunity from arrest. However, the court emphasised that his fundamental rights including right to medical care continue even during custody.",
    fullText: "The petitioner, a sitting Minister in Tamil Nadu Government, was arrested by the ED under PMLA in connection with cash-for-jobs scam...",
    isNew: false,
  },
  {
    id: "j016",
    title: "High Court of Judicature at Madras v. M.C. Subramaniam",
    citation: "2024 (1) CTC 241",
    court: "Madras High Court",
    date: "10 January 2024",
    year: 2024,
    bench: "Full Bench",
    judges: ["Chief Justice S.V. Gangapurwala", "Justice D. Bharatha Chakravarthy", "Justice G.R. Swaminathan"],
    petitioner: "High Court of Judicature at Madras",
    respondent: "M.C. Subramaniam",
    topic: ["Constitutional Law", "Civil Law"],
    acts: ["Constitution of India", "Tamil Nadu Civil Courts Act"],
    headnote: "High Court has supervisory jurisdiction under Article 227 over all courts and tribunals within its territorial jurisdiction.",
    aiSummary: "The Madras High Court Full Bench reaffirmed the supervisory jurisdiction of the High Court under Article 227 of the Constitution over all civil and criminal courts within Tamil Nadu. The court held that this power is wider than appellate jurisdiction and is exercised to prevent miscarriage of justice.",
    fullText: "The Full Bench was constituted to examine the scope of supervisory jurisdiction of the High Court under Article 227...",
    isNew: true,
  },
  {
    id: "j017",
    title: "Gurbaj Singh Sidhu v. State of Punjab",
    citation: "2024 SCCOnLine P&H 1124",
    court: "Punjab & Haryana High Court",
    date: "5 March 2024",
    year: 2024,
    bench: "Single Judge",
    judges: ["Justice Anoop Chitkara"],
    petitioner: "Gurbaj Singh Sidhu",
    respondent: "State of Punjab",
    topic: ["Criminal Law"],
    acts: ["Narcotic Drugs & Psychotropic Substances Act, 1985"],
    headnote: "Strict compliance with Section 50 NDPS mandatory for search of a person; violation vitiates conviction.",
    aiSummary: "The Punjab & Haryana High Court acquitted the accused in an NDPS case holding that the investigating officer's failure to inform the accused of his right to be searched before a Magistrate or Gazetted Officer as required under Section 50 NDPS Act was fatal to the prosecution's case.",
    fullText: "The petitioner was convicted for possession of heroin but challenged the conviction on the ground that mandatory provisions of Section 50 NDPS Act were not followed...",
    isNew: true,
  },
  {
    id: "j018",
    title: "Priya Mathur v. State of Kerala",
    citation: "2024 SCCOnLine Ker 2341",
    court: "Kerala High Court",
    date: "28 February 2024",
    year: 2024,
    bench: "Single Judge",
    judges: ["Justice Bechu Kurian Thomas"],
    petitioner: "Priya Mathur",
    respondent: "State of Kerala",
    topic: ["Family Law", "Human Rights"],
    acts: ["Protection of Women from Domestic Violence Act, 2005", "Hindu Marriage Act, 1955"],
    headnote: "Live-in partner entitled to protection under Domestic Violence Act; relationship akin to marriage entitled to legal recognition.",
    aiSummary: "The Kerala High Court held that a woman in a long-standing live-in relationship is entitled to protection under the Protection of Women from Domestic Violence Act, 2005. The court held that a relationship 'in the nature of marriage' under Section 2(f) includes live-in relationships where the couple has cohabited for a significant period.",
    fullText: "The petitioner sought protection orders under the DV Act against her live-in partner who had started a new relationship and evicted her from the shared home...",
    isNew: true,
  },
];

export const dailyUpdates: DailyUpdate[] = [
  {
    id: "du001",
    title: "SC holds that right to clean environment is enforceable fundamental right under Article 21",
    court: "Supreme Court of India",
    date: "Today",
    topic: ["Constitutional Law", "Environmental Law"],
    citation: "W.P.(C) No. 1093/2024",
    summary: "A three-judge bench held that citizens have an enforceable fundamental right to a clean and healthy environment under Article 21, directing all states to comply with air quality standards.",
    isNew: true,
  },
  {
    id: "du002",
    title: "Delhi HC: Employer must provide written reasons for termination within 7 days",
    court: "Delhi High Court",
    date: "Today",
    topic: ["Labour Law"],
    citation: "W.P.(C) 4521/2024",
    summary: "In a significant ruling, the Delhi High Court directed that all employers must provide written reasons for termination within 7 days of termination order, failing which termination may be challenged as arbitrary.",
    isNew: true,
  },
  {
    id: "du003",
    title: "Bombay HC: WhatsApp group admin not automatically liable for member messages",
    court: "Bombay High Court",
    date: "Today",
    topic: ["Criminal Law"],
    citation: "Cri. Appeal 234/2024",
    summary: "The Bombay High Court held that a WhatsApp group administrator cannot be held vicariously liable for defamatory or offensive messages posted by group members unless the admin actively promoted or forwarded such content.",
    isNew: true,
  },
  {
    id: "du004",
    title: "Madras HC issues guidelines on bail in cybercrime cases",
    court: "Madras High Court",
    date: "Yesterday",
    topic: ["Criminal Law"],
    citation: "Crl.O.P.(MD) 3251/2024",
    summary: "Madras High Court laid down comprehensive guidelines for granting bail in cybercrime cases, emphasising that bail conditions must not prevent the accused from earning a livelihood while also protecting digital evidence.",
    isNew: false,
  },
  {
    id: "du005",
    title: "SC: Daughters have equal right in self-acquired property of deceased Hindu father",
    court: "Supreme Court of India",
    date: "Yesterday",
    topic: ["Family Law", "Property Law"],
    citation: "(2024) SCC OnLine SC 412",
    summary: "Reiterating the 2005 amendment to the Hindu Succession Act, the Supreme Court held that daughters have equal rights in their father's self-acquired property irrespective of whether the father died before or after the 2005 amendment.",
    isNew: false,
  },
  {
    id: "du006",
    title: "Karnataka HC quashes Section 498A FIR filed after 3-year delay without explanation",
    court: "Karnataka High Court",
    date: "Yesterday",
    topic: ["Criminal Law", "Family Law"],
    citation: "Crl.P. 1823/2024",
    summary: "The Karnataka High Court quashed an FIR under Section 498A IPC filed three years after the alleged incidents, noting that unexplained delay in filing a matrimonial complaint raises strong suspicion about its bona fides.",
    isNew: false,
  },
  {
    id: "du007",
    title: "Allahabad HC: No bail cancellation without material change in circumstances",
    court: "Allahabad High Court",
    date: "2 days ago",
    topic: ["Criminal Law"],
    citation: "Bail Cancellation Application No. 542/2024",
    summary: "The Allahabad High Court reiterated that once bail has been granted, it cannot be cancelled unless there is a material change in circumstances or the accused has misused the bail by influencing witnesses or absconding.",
    isNew: false,
  },
  {
    id: "du008",
    title: "Gujarat HC: Builder must refund with 9% interest for project delay beyond 3 years",
    court: "Gujarat High Court",
    date: "2 days ago",
    topic: ["Property Law", "Consumer Rights"],
    citation: "Spl.CA 4231/2024",
    summary: "The Gujarat High Court directed a prominent real estate developer to refund the full amount paid by homebuyers along with 9% per annum interest for a project delayed beyond three years, holding it a clear case of deficiency in service under the Consumer Protection Act.",
    isNew: false,
  },
];

export const bareActs: BareAct[] = [
  {
    id: "a001",
    title: "The Constitution of India",
    shortTitle: "Constitution of India",
    year: 1949,
    ministry: "Ministry of Law and Justice",
    category: "Constitutional",
    sections: 395,
    description: "The supreme law of India, establishing the framework of the Indian government, fundamental rights, directive principles, and duties of citizens.",
    lastAmended: "2019",
  },
  {
    id: "a002",
    title: "The Indian Penal Code, 1860",
    shortTitle: "IPC, 1860",
    year: 1860,
    ministry: "Ministry of Home Affairs",
    category: "Criminal",
    sections: 511,
    description: "The main criminal code of India covering offences and punishments for crimes committed within the country.",
    lastAmended: "2013",
  },
  {
    id: "a003",
    title: "The Code of Criminal Procedure, 1973",
    shortTitle: "CrPC, 1973",
    year: 1973,
    ministry: "Ministry of Home Affairs",
    category: "Criminal",
    sections: 484,
    description: "Provides the procedure for administration of criminal law in India including investigation, trial, and appeal processes.",
    lastAmended: "2018",
  },
  {
    id: "a004",
    title: "The Code of Civil Procedure, 1908",
    shortTitle: "CPC, 1908",
    year: 1908,
    ministry: "Ministry of Law and Justice",
    category: "Civil",
    sections: 158,
    description: "Regulates the procedure for courts trying civil cases in India, including suits, appeals, and execution of decrees.",
    lastAmended: "2018",
  },
  {
    id: "a005",
    title: "The Indian Contract Act, 1872",
    shortTitle: "Contract Act, 1872",
    year: 1872,
    ministry: "Ministry of Law and Justice",
    category: "Civil",
    sections: 238,
    description: "Governs the law relating to contracts in India, covering formation, validity, breach, and remedies for breach of contracts.",
    lastAmended: "1997",
  },
  {
    id: "a006",
    title: "The Transfer of Property Act, 1882",
    shortTitle: "TP Act, 1882",
    year: 1882,
    ministry: "Ministry of Law and Justice",
    category: "Property",
    sections: 137,
    description: "Defines and amends certain parts of the law relating to transfer of property by act of parties in India.",
    lastAmended: "1929",
  },
  {
    id: "a007",
    title: "The Companies Act, 2013",
    shortTitle: "Companies Act, 2013",
    year: 2013,
    ministry: "Ministry of Corporate Affairs",
    category: "Company Law",
    sections: 470,
    description: "Governs incorporation, responsibilities, directors, and dissolution of companies in India.",
    lastAmended: "2020",
  },
  {
    id: "a008",
    title: "The Right to Information Act, 2005",
    shortTitle: "RTI Act, 2005",
    year: 2005,
    ministry: "Ministry of Personnel",
    category: "Constitutional",
    sections: 31,
    description: "Provides for setting out the practical regime of right to information for citizens to secure access to information under the control of public authorities.",
    lastAmended: "2019",
  },
  {
    id: "a009",
    title: "The Protection of Children from Sexual Offences Act, 2012",
    shortTitle: "POCSO Act, 2012",
    year: 2012,
    ministry: "Ministry of Women and Child Development",
    category: "Criminal",
    sections: 46,
    description: "Provides protection to children from offences of sexual assault, sexual harassment and pornography.",
    lastAmended: "2019",
  },
  {
    id: "a010",
    title: "The Insolvency and Bankruptcy Code, 2016",
    shortTitle: "IBC, 2016",
    year: 2016,
    ministry: "Ministry of Corporate Affairs",
    category: "Banking & Finance",
    sections: 255,
    description: "Consolidates and amends the laws relating to reorganisation and insolvency resolution of corporate persons, partnership firms and individuals.",
    lastAmended: "2021",
  },
  {
    id: "a011",
    title: "The Hindu Marriage Act, 1955",
    shortTitle: "Hindu Marriage Act",
    year: 1955,
    ministry: "Ministry of Law and Justice",
    category: "Family Law",
    sections: 29,
    description: "Governs marriage and divorce among Hindus, Buddhists, Jains, and Sikhs in India.",
    lastAmended: "2019",
  },
  {
    id: "a012",
    title: "The Income Tax Act, 1961",
    shortTitle: "Income Tax Act",
    year: 1961,
    ministry: "Ministry of Finance",
    category: "Tax Law",
    sections: 298,
    description: "The charging statute of income tax in India governing levy, administration, collection and recovery of income tax.",
    lastAmended: "2023",
  },
];

export const actCategories = [
  "Constitutional", "Criminal", "Civil", "Family Law",
  "Property", "Company Law", "Tax Law", "Labour Law",
  "Banking & Finance", "Environmental", "Intellectual Property",
];
